baseURL: 'https://www.ipalo.it/gasbrugherio/'
languageCode: it-it
title: GAS Brugherio
theme: minimal
params:
  author: Paolo Rossi
  description: Gruppo di Acquisto Solidale "Cent coo cent crap"
  accent: '#0A81D1'
  showBorder: true
  backgroundColor: white
  font: Raleway
  highlight: true
outputFormats:
  HTML:
    mediaType: text/html
minify:
    disableXML: true
menu:
  main:
    - url: /
      name: Home
      weight: 1
    - url: /ordini/
      name: Ordini
      weight: 2
disableKinds:
  - taxonomy
contentTypes:
  - text/html: {}
